### ISSUE TITLE
Implement the Parser functor

### ISSUE THREAD

**Issue by rizo** [fold-lang/fold#9]
**Motivation**: Pratt uses a custom state, with token stream and environment, while the original Parser only includes the token stream.

**Implementation**: Try implementing Parser as a functor for a given `State` and defining all the parser combinators on top. Pratt would do `include Parser.Make(Pratt.State)` and avoid the reimplementation of all combinators.

**Comment by rizo** [comment]
**Tasks**:

- [x] Parser functor (2a916046bfeff5aa583deb619c4138ec56aa16e9)
- [x] Use parser functor in Pratt

**Comment by drinkless** [comment]
@rizo You can do this manually by yourself, of course.

**Comment by rizo** [comment]
@LyablinNikita what _exactly_ do you mean?
